import { Hono } from 'hono'
import { analyticsRouter } from './routes/analytics'
import { articlesRouter } from './routes/articles'
import { fileURLToPath } from 'url'
import { graphqlRouter } from './routes/graphql'
import path from 'path'
import { publishersRouter } from './routes/articles'
import { serve } from '@hono/node-server'
import { spawn } from 'child_process'
import { streamRouter } from './routes/stream'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)
const app = new Hono()

// Mount routes
const api = app
  .route('/api/publishers', publishersRouter)
  .route('/api/articles', articlesRouter)
  .route('/api/analytics', analyticsRouter)
  .route('/api/stream', streamRouter)
  .route('/api/graphql', graphqlRouter)

/////////////////////////////////////////////////
/////////////////////////////////////////////////
/////////////////////////////////////////////////

// app.post('/login', async (c) => {
//   try {
//     await authorize(c)
//   } catch (cause) {
//     throw new HTTPException(401, { message, cause })
//   }
//   return c.redirect('/')
// })

// app.onError((err, c) => {
//   if (err instanceof HTTPException) {
//     // Return the error response generated by HTTPException
//     return err.getResponse()
//   }
//   // For any other unexpected errors, log and return a generic 500 response
//   console.error(err)
//   return c.text('Internal Server Error', 500)
// })

// export const zValidator = <T extends z.ZodSchema, Target extends keyof ValidationTargets>(
//   target: Target,
//   schema: T
// ) =>
//   zv(target, schema, (result) => {
//     if (!result.success) {
//       throw new HTTPException(400, { cause: result.error, message: 'Unauthorized' })
//     }
//   })

/////////////////////////////////////////////////
/////////////////////////////////////////////////
/////////////////////////////////////////////////

export type AppType = typeof api

const port = 3001
console.log(`Server is running on port ${port}`)
const server = serve({
  fetch: app.fetch,
  port,
})

// graceful shutdown
process.on('SIGINT', () => {
  server.close()
  process.exit(0)
})

process.on('SIGTERM', () => {
  server.close((err) => {
    if (err) {
      console.error(err)
      process.exit(1)
    }
    process.exit(0)
  })
})

// Spawn long-running scraper process
const scraperProcess = spawn('npx', ['tsx', 'server/scrape.ts'], {
  stdio: 'inherit',
  cwd: path.resolve(dirname, '..'),
  shell: true,
})
scraperProcess.on('error', (err) => {
  console.error('Failed to start scraper process:', err)
})
scraperProcess.on('exit', (code) => {
  console.log(`Scraper process exited with code ${code}`)
})

// // Spawn Drizzle Studio process
// const dbStudioroPcess = spawn('npx', ['drizzle-kit', 'studio'], {
//   stdio: 'inherit',
//   cwd: path.resolve(dirname, '..'),
//   shell: true,
// })
// dbStudioProcess.on('error', (err) => {
//   console.error('Failed to start Drizzle Studio process:', err)
// })
// dbStudioProcess.on('exit', (code) => {
//   console.log(`Drizzle Studio process exited with code ${code}`)
// })
