import { Hono } from 'hono'
import { articlesRouter } from './routes/articlesRouter'
import { fileURLToPath } from 'url'
import { graphqlRouter } from './routes/graphql'
import path from 'path'
import { publishersRouter } from './routes/publishersRouter'
import { serve } from '@hono/node-server'
import { streamRouter } from './routes/stream'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

const app = new Hono()
  .route('/api/stream', streamRouter)
  .route('/api/graphql', graphqlRouter)
  .route('/api/publishers', publishersRouter)
  .route('/api/articles', articlesRouter)

/////////////////////////////////////////////////
/////////////////////////////////////////////////
/////////////////////////////////////////////////

// app.post('/login', async (c) => {
//   try {
//     await authorize(c)
//   } catch (cause) {
//     throw new HTTPException(401, { message, cause })
//   }
//   return c.redirect('/')
// })

// app.onError((err, c) => {
//   if (err instanceof HTTPException) {
//     // Return the error response generated by HTTPException
//     return err.getResponse()
//   }
//   // For any other unexpected errors, log and return a generic 500 response
//   console.error(err)
//   return c.text('Internal Server Error', 500)
// })

// export const zValidator = <T extends z.ZodSchema, Target extends keyof ValidationTargets>(
//   target: Target,
//   schema: T
// ) =>
//   zv(target, schema, (result) => {
//     if (!result.success) {
//       throw new HTTPException(400, { cause: result.error, message: 'Unauthorized' })
//     }
//   })

/////////////////////////////////////////////////
/////////////////////////////////////////////////
/////////////////////////////////////////////////

export type AppType = typeof app

const port = 3001
console.log(`Server is running on port ${port}`)
const server = serve({
  fetch: app.fetch,
  port,
})

// graceful shutdown
process.on('SIGINT', () => {
  server.close()
  process.exit(0)
})

process.on('SIGTERM', () => {
  server.close((err) => {
    if (err) {
      console.error(err)
      process.exit(1)
    }
    process.exit(0)
  })
})
