CREATE ROLE "admin";--> statement-breakpoint
CREATE ROLE "guest";--> statement-breakpoint
CREATE ROLE "user";--> statement-breakpoint
CREATE TABLE "articles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "articles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"deleted_at" timestamp,
	"publisher_id" integer NOT NULL,
	"pathname" text NOT NULL,
	"published_at" timestamp NOT NULL,
	"category" text NOT NULL,
	"heading" text NOT NULL,
	"summary" text NOT NULL,
	"debaited_heading" text,
	"debaited_summary" text
);
--> statement-breakpoint
CREATE TABLE "publishers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "publishers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"deleted_at" timestamp,
	"name" text NOT NULL,
	"url" text NOT NULL,
	CONSTRAINT "publishers_url_unique" UNIQUE("url")
);
--> statement-breakpoint
CREATE TABLE "tenants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tenants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"deleted_at" timestamp,
	"name" text NOT NULL,
	CONSTRAINT "tenants_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "tenants" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"deleted_at" timestamp,
	"event" text NOT NULL,
	"article_id" integer
);
--> statement-breakpoint
ALTER TABLE "articles" ADD CONSTRAINT "articles_publisher_id_publishers_id_fk" FOREIGN KEY ("publisher_id") REFERENCES "public"."publishers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_events" ADD CONSTRAINT "user_events_article_id_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."articles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "idx_publisher_pathname" ON "articles" USING btree ("publisher_id","pathname");--> statement-breakpoint
CREATE POLICY "crud-admin-policy-select" ON "tenants" AS PERMISSIVE FOR SELECT TO "admin" USING (true);--> statement-breakpoint
CREATE POLICY "crud-admin-policy-insert" ON "tenants" AS PERMISSIVE FOR INSERT TO "admin" WITH CHECK (false);--> statement-breakpoint
CREATE POLICY "crud-admin-policy-update" ON "tenants" AS PERMISSIVE FOR UPDATE TO "admin" USING (false) WITH CHECK (false);--> statement-breakpoint
CREATE POLICY "crud-admin-policy-delete" ON "tenants" AS PERMISSIVE FOR DELETE TO "admin" USING (false);