name: Checks

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Type check
        run: yarn typecheck

      - name: Lint check
        run: yarn lint

      - name: Format check
        run: yarn format-all:check

      - name: Check Knip
        run: yarn check:knip

      - name: Test
        run: yarn test
