name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: corepack enable && yarn install

      - name: eslint
        run: yarn lint:check

      - name: prettier
        run: yarn format:check:all

      - name: typecheck
        run: yarn typecheck

      - name: test
        run: yarn test
